# Generated by Django 2.2.24 on 2021-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tictet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number_of_person', models.IntegerField()),
                ('date', models.DateField()),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('Luxury', 'Luxury'), ('Basic', 'Basic'), ('Normal', 'Normal')], max_length=100)),
            ],
        ),
    ]
